---
# tasks file for update_server
#
- name         : "|___INSTALLING YUM PACAGES___|"
  yum          :
    name       : "{{packages}}"
  vars:
    packages:
      - epel-release
      - python
      - mariadb-server
      - python-pip
    state: lates
- name         : "|___INSTALLING PIP PACKAGES___|"
  shell        : pip install PyMySQL

- name         :
  service      : 
    name       : mariadb 
    state      : started 
    enabled    : yes

- name         : "|___CHECK MYSQL INSTALLATION___|"
  mysql_info   :
    login_user : root
  register     : mysql_install_info

- debug    :
    msg    : "{{mysql_install_info.version}}"

