---
# tasks file for postadm_install
- name         : "|___CHECK POSTFIXADMIN DIRECTORY___|"
  stat         :
    path       : "{{installing_path}}/postfixadmin" 
  register     : exdir
- debug        :
    msg        : "POSTFIXADMIN DIRECTORY EXIST..."
  when         : exdir.stat.exists
- debug        :
    msg        : "POSTFIXADMIN DIRECTORY DIDN'T EXIST"
  when         : exdir.stat.exists == False

- name         : "|___CHECK BACKUP DIRECTORY___|"
  stat         :
    path       : /MAIL_SERVER_BACKUP
  register     : exdirmail
- debug        :
    msg        : "BACKUP DIRECTORY EXIST..."
  when         : exdirmail.stat.exists
- debug        :
    msg        : "BACKUP DIRECTORY DIDN'T EXIST"
  when         : exdirmail.stat.exists == False

- name         : "|___CREATE BACKUP POSTFIXADMIN DIRECTORY___|"
  shell        :
    cmd        : mkdir /MAIL_SERVER_BACKUP/
  when         : exdirmail.stat.exists == False

- name         : "|___CREATE BACKUP DIRECTORY___|"
  shell        :
    cmd        : mkdir /MAIL_SERVER_BACKUP/
  when         : exdirmail.stat.exists == False

- name         : "|___CREATE BACKUP POSTFIXADMIN DIRECTORY___|"
  shell        :
    cmd        : "cp -Rp {{installing_path}} /MAIL_SERVER_BACKUP/"
  when         : exdir.stat.exists == True

- name         : "|___INSTALL POSTFIXADMIN___|"
  copy         :
    src        : postfixadmin_3_1.tar.gz
    dest       : "{{installing_path}}"
  when         : exdir.stat.exists == False

- name         : "|___INSTALL POSTFIXADMIN___|"
  shell        :
    cmd        : "cd {{installing_path}} && tar -xf postfixadmin_3_1.tar.gz"
  when         : exdir.stat.exists == False

- name         : "|___CREATE DB_USER FOR POSTFIXADMIN___|"
  mysql_user   :
    name       : "{{postfixadmin_user}}"
    password   : "{{postfixadmin_password}}"
    priv       : '{{postfix_dbname}}.*:ALL'
    state      : present

- name         : "|___COPING CUSTOM FILES TO POSTFIXADMIN___|"
  template     :
    src        : config.inc.php.j2
    dest       : "{{installing_path}}/postfixadmin/config.inc.php"

- name         : "|___CHECK TEMPLATE DIRECTORY___|"
  stat         :
    path       : "{{installing_path}}/postfixadmin/templates_c/"
  register     : exdirtemp

- name         : "|___CREATE template_c___|"
  shell        :
    cmd        : "mkdir {{installing_path}}/postfixadmin/templates_c/ && chmod 777 {{installing_path}}/postfixadmin/templates_c/"
  when         : exdirtemp.stat.exists == False


- name         : "|___CHECK MAIL DIRECTORY___|"
  stat         :
    path       : "/var/vmail"
  register     : exdirvm

- name         : "|___CREATE MAIL___|"
  shell        :
    cmd        : "mkdir /var/vmail/ && chown -R mail: /var/vmail && service postfix restart"
  when         : exdirvm.stat.exists == False
